name: Build and Push NuGet Package

on:
  push:
    branches:
      - main
      - master 
  pull_request:

jobs:
  build-push-nuget:
    name: Build and Push NuGet Package
    uses: drdk/github-workflows-dotnet/.github/workflows/build-push-nuget.yml@main
    secrets: inherit
    with:
      packageProject: "NLog.Slack"
      testProject: "NLog.Slack.Tests"